[build]
  base = "."
  command = "npm run build:netlify"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

  # Netlify Functions folder where built lambda handlers will be copied
  FUNCTIONS_DIR = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
